[2023-06-07T19:22:05.120+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: open_brewery_pipeline.data_load manual__2023-06-07T19:21:35.500949+00:00 [queued]>
[2023-06-07T19:22:05.136+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: open_brewery_pipeline.data_load manual__2023-06-07T19:21:35.500949+00:00 [queued]>
[2023-06-07T19:22:05.138+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T19:22:05.158+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): data_load> on 2023-06-07 19:21:35.500949+00:00
[2023-06-07T19:22:05.166+0000] {standard_task_runner.py:57} INFO - Started process 3345 to run task
[2023-06-07T19:22:05.171+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'open_brewery_pipeline', 'data_load', 'manual__2023-06-07T19:21:35.500949+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/open_brewery_pipeline.py', '--cfg-path', '/tmp/tmp4h3ca463']
[2023-06-07T19:22:05.175+0000] {standard_task_runner.py:85} INFO - Job 63: Subtask data_load
[2023-06-07T19:22:05.244+0000] {task_command.py:410} INFO - Running <TaskInstance: open_brewery_pipeline.data_load manual__2023-06-07T19:21:35.500949+00:00 [running]> on host a2d5081e771c
[2023-06-07T19:22:05.355+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='open_brewery_pipeline' AIRFLOW_CTX_TASK_ID='data_load' AIRFLOW_CTX_EXECUTION_DATE='2023-06-07T19:21:35.500949+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-07T19:21:35.500949+00:00'
[2023-06-07T19:22:05.359+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-07T19:22:05.361+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/scripts/load.py ']
[2023-06-07T19:22:05.377+0000] {subprocess.py:86} INFO - Output:
[2023-06-07T19:22:06.272+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.7/site-packages/google/auth/_default.py:78: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
[2023-06-07T19:22:06.273+0000] {subprocess.py:93} INFO -   warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
[2023-06-07T19:22:06.278+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-06-07T19:22:06.279+0000] {subprocess.py:93} INFO -   File "/opt/scripts/load.py", line 44, in <module>
[2023-06-07T19:22:06.281+0000] {subprocess.py:93} INFO -     main()
[2023-06-07T19:22:06.282+0000] {subprocess.py:93} INFO -   File "/opt/scripts/load.py", line 41, in main
[2023-06-07T19:22:06.283+0000] {subprocess.py:93} INFO -     upload_blob("open_brewery", "./***/scripts/data.txt", "brewery_data")
[2023-06-07T19:22:06.284+0000] {subprocess.py:93} INFO -   File "/opt/scripts/load.py", line 33, in upload_blob
[2023-06-07T19:22:06.285+0000] {subprocess.py:93} INFO -     blob.upload_from_filename(source_file_name, if_generation_match=generation_match_precondition)
[2023-06-07T19:22:06.286+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2682, in upload_from_filename
[2023-06-07T19:22:06.287+0000] {subprocess.py:93} INFO -     with open(filename, "rb") as file_obj:
[2023-06-07T19:22:06.289+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: './***/scripts/data.txt'
[2023-06-07T19:22:06.333+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-07T19:22:06.349+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-07T19:22:06.358+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=open_brewery_pipeline, task_id=data_load, execution_date=20230607T192135, start_date=20230607T192205, end_date=20230607T192206
[2023-06-07T19:22:06.374+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 63 for task data_load (Bash command failed. The command returned a non-zero exit code 1.; 3345)
[2023-06-07T19:22:06.389+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-07T19:22:06.412+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
